// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Banchou.Pawn
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class PawnFrameDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Banchou.Pawn.PawnFrameData>
    {


        public void Serialize(ref MessagePackWriter writer, global::Banchou.Pawn.PawnFrameData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(9);
            formatterResolver.GetFormatterWithVerify<global::Banchou.Pawn.PawnId>().Serialize(ref writer, value.PawnId, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<int>>().Serialize(ref writer, value.StateHashes, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<float>>().Serialize(ref writer, value.NormalizedTimes, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<int, float>>().Serialize(ref writer, value.Floats, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<int, bool>>().Serialize(ref writer, value.Bools, options);
            formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<int, int>>().Serialize(ref writer, value.Ints, options);
            formatterResolver.GetFormatterWithVerify<global::UnityEngine.Vector3>().Serialize(ref writer, value.Position, options);
            formatterResolver.GetFormatterWithVerify<global::UnityEngine.Vector3>().Serialize(ref writer, value.Forward, options);
            writer.Write(value.When);
        }

        public global::Banchou.Pawn.PawnFrameData Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __PawnId__ = default(global::Banchou.Pawn.PawnId);
            var __StateHashes__ = default(global::System.Collections.Generic.List<int>);
            var __NormalizedTimes__ = default(global::System.Collections.Generic.List<float>);
            var __Floats__ = default(global::System.Collections.Generic.Dictionary<int, float>);
            var __Bools__ = default(global::System.Collections.Generic.Dictionary<int, bool>);
            var __Ints__ = default(global::System.Collections.Generic.Dictionary<int, int>);
            var __Position__ = default(global::UnityEngine.Vector3);
            var __Forward__ = default(global::UnityEngine.Vector3);
            var __When__ = default(float);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __PawnId__ = formatterResolver.GetFormatterWithVerify<global::Banchou.Pawn.PawnId>().Deserialize(ref reader, options);
                        break;
                    case 1:
                        __StateHashes__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<int>>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __NormalizedTimes__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.List<float>>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __Floats__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<int, float>>().Deserialize(ref reader, options);
                        break;
                    case 4:
                        __Bools__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<int, bool>>().Deserialize(ref reader, options);
                        break;
                    case 5:
                        __Ints__ = formatterResolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<int, int>>().Deserialize(ref reader, options);
                        break;
                    case 6:
                        __Position__ = formatterResolver.GetFormatterWithVerify<global::UnityEngine.Vector3>().Deserialize(ref reader, options);
                        break;
                    case 7:
                        __Forward__ = formatterResolver.GetFormatterWithVerify<global::UnityEngine.Vector3>().Deserialize(ref reader, options);
                        break;
                    case 8:
                        __When__ = reader.ReadSingle();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Banchou.Pawn.PawnFrameData();
            ____result.PawnId = __PawnId__;
            ____result.StateHashes = __StateHashes__;
            ____result.NormalizedTimes = __NormalizedTimes__;
            ____result.Floats = __Floats__;
            ____result.Bools = __Bools__;
            ____result.Ints = __Ints__;
            ____result.Position = __Position__;
            ____result.Forward = __Forward__;
            ____result.When = __When__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
